// Generated by test5.test1.tools.generate_typescript_defs
// Source of truth: test5/test1/python/llm_structured.py (thin wrapper) + C++ core
//
// This file intentionally focuses on TYPES (not runtime validation).

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

export interface ValidationError {
  kind?: 'schema' | 'type' | 'limit' | 'parse';
  message: string;
  path: string; // e.g. $.items[0].id
  jsonPointer?: string; // e.g. /items/0/id
  limit?: { kind: 'maxBufferBytes' | 'maxItems'; current: number; max: number };
}

export type JsonSchema = {
  type?: 'object' | 'array' | 'string' | 'number' | 'integer' | 'boolean' | 'null';
  enum?: Json[];
  const?: Json;
  allOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  if?: JsonSchema;
  then?: JsonSchema;
  else?: JsonSchema;
  dependentRequired?: Record<string, string[]>;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  default?: Json;
  additionalProperties?: boolean | JsonSchema;
  propertyNames?: JsonSchema;
  items?: JsonSchema;
  minItems?: number;
  maxItems?: number;
  contains?: JsonSchema;
  minContains?: number;
  maxContains?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  format?: 'email' | 'uuid' | 'date-time' | (string & {});
  minimum?: number;
  maximum?: number;
  multipleOf?: number;
  minProperties?: number;
  maxProperties?: number;
};

export interface MarkdownValidationSchema {
  requiredHeadings?: string[];
  forbidHtml?: boolean;
  maxLineLength?: number;
  minCodeBlocks?: number;
  maxCodeBlocks?: number;
  requiredCodeFences?: string[];
  minTables?: number;
  requireTaskList?: boolean;
  sections?: Record<string, {
    minLength?: number;
    maxLength?: number;
    requireBullets?: boolean;
    minBullets?: number;
    maxBullets?: number;
  }>;
}

export interface MarkdownParsed {
  text: string;
  lines: string[];
  headings: Array<{ level: number; title: string; line: number }>;
  sections: Record<string, string[]>;
  codeBlocks: Array<{ lang: string; body: string }>;
  bulletLineNumbers: number[];
  taskLineNumbers: number[];
  tables: Array<{ startLine: number; raw: string }>;
}

export interface KeyValueSchema {
  required?: string[];
  allowExtra?: boolean;
  patterns?: Record<string, string>; // key -> regex
  enum?: Record<string, string[]>;
}

export interface SqlValidationSchema {
  allowedStatements?: string[];
  forbidKeywords?: string[];
  forbidComments?: boolean;
  forbidSemicolon?: boolean;
  requireFrom?: boolean;
  requireWhere?: boolean;
  requireLimit?: boolean;
  maxLimit?: number;
  forbidUnion?: boolean;
  forbidSubqueries?: boolean;
  allowedTables?: string[];
  forbidSelectStar?: boolean;
  requireWhereColumns?: string[];
  forbidSchemas?: string[];
  forbidCrossJoin?: boolean;
  forbidSelectWithoutLimit?: boolean;
  requireOrderBy?: boolean;
  requireWherePatterns?: string[];
  forbidTables?: string[];

  // Hardened SQL safety options.
  maxJoins?: number;
  allowedJoinTypes?: string[];
  forbidOrTrue?: boolean;
  placeholderStyle?: 'qmark' | 'dollar' | 'either';
  forbidFunctions?: boolean | string[];
  allowedColumns?: string[];
  allowUnqualifiedColumns?: boolean;
}

export interface SqlParsed {
  sql: string;
  statementType: string;
  hasWhere: boolean;
  hasFrom: boolean;
  hasLimit: boolean;
  limit: number | null;
  hasUnion: boolean;
  hasComments: boolean;
  hasSubquery: boolean;
  tables: string[];
}

// ---- Convenience: example schema to type
// You can generate your own types using `schema_to_ts` in Python.

export type ExamplePlan = {
  title: string;
  steps:
  Array<
    {
      id: number;
      text: string;
    }
  >;
};
